language: rust
cache: cargo
sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux

before_install:
  - git submodule update --init --recursive

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
