language: rust
cache: cargo
sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux

install: ci/install-pmdk.sh

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
